### ISSUE TITLE
Issue links are not generated for some students.

### ISSUE THREAD

**Issue by amaseda** [wdidc/assignments#11]
Ex.: https://github.com/ga-dc/tic_tac_toe/pull/12

In the above example, Nayana's pull request follows protocol but does not generate an issue link @ http://assignments.wdidc.org/assignments/25.

**Comment by jshawl** [comment]
https://api.github.com/repos/ga-dc/tic_tac_toe/issues?state=all

**Comment by jshawl** [comment]
this is a pagination issue; fix in progress
