### ISSUE TITLE
No indication of issue when marking item Complete (but not logged in)

### ISSUE THREAD

**Issue by mattscilipoti** [wdidc/assignments#7]
Yesterday, I was marking student's assignments as complete, but they were not persisted (no indication - I just noticed it today).  During testing, I was able to duplicate this by marking as "Complete!" when not logged in.  I expect this is what I did yesterday.
- improve error handling
- should students be able to see each other's assignment status?

**Comment by jshawl** [comment]
Closing for now, as this is no longer an issue i believe with our before action - https://github.com/wdidc/assignments/blob/883bb7e8e0f5cd63556a1dbae163186e237c442b/app/controllers/application_controller.rb#L27-L32
